### ISSUE TITLE
getCellData

### ISSUE THREAD

**Issue by baghzaad** [ssirekumar/POIRE#4]
getCellData does not work with column header...below code returns null....kindly advice

`System.out.println(ExcelDataEngine.getCellData(fileObject.getAbsolutePath(), "Summary", 0, "A")); 
System.out.println(ExcelDataEngine.getCellData(fileObject.getAbsolutePath(), "Summary", 0,"State" ));`

**Comment by ssirekumar** [comment]
@baghzaad,
Here whats you have to do is the 3rd parameter should be 0 indexed based but in 0 index of excel have header data so When ever you want to read particular cell data with column header you have to give proper row value. And one more thing just check your excel sheet have a cell data or not if not its give you empty data.

**Comment by ssirekumar** [comment]
These methods will work only file which is created by Microsoft Excel Not by open-office. I will fix this in next build.
